config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
Rails.application.routes.draw do
  resources :favorites
  resource :schedule
  resources :shopping_carts
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users
  root to: "schedules#show"
end

app/models/shopping_cart.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
class ShoppingCart < ApplicationRecord
  belongs_to :user
end

app/controllers/shopping_carts_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: %i[show edit update destroy]

  # GET /shopping_carts or /shopping_carts.json
  def index
    @shopping_carts = ShoppingCart.all
  end

  # GET /shopping_carts/1 or /shopping_carts/1.json
  def show
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts or /shopping_carts.json
  def create
    @shopping_cart = ShoppingCart.new(shopping_cart_params)

    respond_to do |format|
      if @shopping_cart.save
        format.html { redirect_to @shopping_cart, notice: "Shopping cart was successfully created." }
        format.json { render :show, status: :created, location: @shopping_cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_carts/1 or /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to @shopping_cart, notice: "Shopping cart was successfully updated." }
        format.json { render :show, status: :ok, location: @shopping_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1 or /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_url, notice: "Shopping cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shopping_cart
    @shopping_cart = ShoppingCart.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shopping_cart_params
    params.require(:shopping_cart).permit(:user_id)
  end
end

app/views/shopping_carts/_form.html.erb
<%= simple_form_for(@shopping_cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shopping_carts/_shopping_cart.html.erb
<div id="<%= dom_id shopping_cart %>">
  <p>
    <strong>User:</strong>
    <%= shopping_cart.user_id %>
  </p>

  <p>
    <%= link_to "Show this shopping cart", shopping_cart %>
  </p>
</div>

app/views/shopping_carts/edit.html.erb
<h1>Editing shopping cart</h1>

<%= render "form", shopping_cart: @shopping_cart %>

<br>

<div>
  <%= link_to "Show this shopping cart", @shopping_cart %> |
  <%= link_to "Back to shopping carts", shopping_carts_path %>
</div>

app/views/shopping_carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shopping carts</h1>

<div id="shopping_carts">
  <%= render @shopping_carts %>
</div>

<%= link_to "New shopping cart", new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New shopping cart</h1>

<%= render "form", shopping_cart: @shopping_cart %>

<br>

<div>
  <%= link_to "Back to shopping carts", shopping_carts_path %>
</div>

app/views/shopping_carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shopping_cart %>

<div>
  <%= link_to "Edit this shopping cart", edit_shopping_cart_path(@shopping_cart) %> |
  <%= link_to "Back to shopping carts", shopping_carts_path %>

  <%= button_to "Destroy this shopping cart", shopping_cart_path(@shopping_cart), method: :delete %>
</div>