config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
Rails.application.routes.draw do
  resources :favorites
  resource :schedule
  resources :shopping_carts
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users
  root to: "schedules#show"
end

app/models/venue.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
# == Schema Information
#
# Table name: venues
#
#  id            :bigint           not null, primary key
#  description   :text
#  name          :string
#  rows          :integer
#  seats_per_row :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Venue < ApplicationRecord
end

app/controllers/venues_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]

  # GET /venues or /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1 or /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues or /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: "Venue was successfully created." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def venue_params
    params.require(:venue).permit(:name, :description, :rows, :seats_per_row)
  end
end

app/views/venues/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :rows %>
    <%= f.input :seats_per_row %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/venues/_venue.html.erb
<div id="<%= dom_id venue %>">
  <p>
    <strong>Name:</strong>
    <%= venue.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= venue.description %>
  </p>

  <p>
    <strong>Rows:</strong>
    <%= venue.rows %>
  </p>

  <p>
    <strong>Seats per row:</strong>
    <%= venue.seats_per_row %>
  </p>

  <p>
    <%= link_to "Show this venue", venue %>
  </p>
</div>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render "form", venue: @venue %>

<br>

<div>
  <%= link_to "Show this venue", @venue %> |
  <%= link_to "Back to venues", venues_path %>
</div>

app/views/venues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Venues</h1>

<div id="venues">
  <%= render @venues %>
</div>

<%= link_to "New venue", new_venue_path %>

app/views/venues/new.html.erb
<h1 class="text-2xl font-bold">New venue</h1>

<%= render "form", venue: @venue %>

<br>

<div>
  <%= link_to "Back to venues", venues_path %>
</div>

app/views/venues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @venue %>

<div>
  <%= link_to "Edit this venue", edit_venue_path(@venue) %> |
  <%= link_to "Back to venues", venues_path %>

  <%= button_to "Destroy this venue", venue_path(@venue), method: :delete %>
</div>