config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
Rails.application.routes.draw do
  resources :favorites
  resource :schedule
  resources :shopping_carts
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users
  root to: "schedules#show"
end

app/models/band.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
# == Schema Information
#
# Table name: bands
#
#  id          :bigint           not null, primary key
#  description :text
#  genre_tags  :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Band < ApplicationRecord
  def genres
    genre_tags.split(",")
  end
end

app/controllers/bands_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
class BandsController < ApplicationController
  before_action :set_band, only: %i[show edit update destroy]

  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_band
    @band = Band.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def band_params
    params.require(:band).permit(:name, :description, :genre_tags)
  end
end

app/views/bands/_band.html.erb
<div id="<%= dom_id band %>">
  <p>
    <strong>Name:</strong>
    <%= band.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= band.description %>
  </p>

  <p>
    <strong>Genre tags:</strong>
    <%= band.genre_tags %>
  </p>

  <p>
    <%= link_to "Show this band", band %>
  </p>
</div>

app/views/bands/_form.html.erb
<%= simple_form_for(@band) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :genre_tags %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Show this band", @band %> |
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/bands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bands</h1>

<div id="bands">
  <%= render @bands %>
</div>

<%= link_to "New band", new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/bands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @band %>

<div>
  <%= link_to "Edit this band", edit_band_path(@band) %> |
  <%= link_to "Back to bands", bands_path %>

  <%= button_to "Destroy this band", band_path(@band), method: :delete %>
</div>