config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
Rails.application.routes.draw do
  resources :favorites
  resource :schedule
  resources :shopping_carts
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users
  root to: "schedules#show"
end

app/models/ticket_order.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
# == Schema Information
#
# Table name: ticket_orders
#
#  id                :bigint           not null, primary key
#  count             :integer
#  status            :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  concert_id        :bigint           not null
#  shopping_carts_id :bigint
#
class TicketOrder < ApplicationRecord
  belongs_to :concert
  belongs_to :shopping_cart
end

app/controllers/ticket_orders_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
class TicketOrdersController < ApplicationController
  before_action :set_ticket_order, only: %i[show edit update destroy]

  # GET /ticket_orders or /ticket_orders.json
  def index
    @ticket_orders = TicketOrder.all
  end

  # GET /ticket_orders/1 or /ticket_orders/1.json
  def show
  end

  # GET /ticket_orders/new
  def new
    @ticket_order = TicketOrder.new
  end

  # GET /ticket_orders/1/edit
  def edit
  end

  # POST /ticket_orders or /ticket_orders.json
  def create
    @ticket_order = TicketOrder.new(ticket_order_params)

    respond_to do |format|
      if @ticket_order.save
        format.html { redirect_to @ticket_order, notice: "Ticket order was successfully created." }
        format.json { render :show, status: :created, location: @ticket_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_orders/1 or /ticket_orders/1.json
  def update
    respond_to do |format|
      if @ticket_order.update(ticket_order_params)
        format.html { redirect_to @ticket_order, notice: "Ticket order was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_orders/1 or /ticket_orders/1.json
  def destroy
    @ticket_order.destroy
    respond_to do |format|
      format.html { redirect_to ticket_orders_url, notice: "Ticket order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket_order
    @ticket_order = TicketOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_order_params
    params.require(:ticket_order).permit(:concert_id, :statusinteger, :scount, :shopping_cart_id)
  end
end

app/views/ticket_orders/_form.html.erb
<%= simple_form_for(@ticket_order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :concert %>
    <%= f.input :statusinteger %>
    <%= f.input :scount %>
    <%= f.association :shopping_cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_orders/_ticket_order.html.erb
<div id="<%= dom_id ticket_order %>">
  <p>
    <strong>Concert:</strong>
    <%= ticket_order.concert_id %>
  </p>

  <p>
    <strong>Statusinteger:</strong>
    <%= ticket_order.statusinteger %>
  </p>

  <p>
    <strong>Scount:</strong>
    <%= ticket_order.scount %>
  </p>

  <p>
    <strong>Shopping cart:</strong>
    <%= ticket_order.shopping_cart_id %>
  </p>

  <p>
    <%= link_to "Show this ticket order", ticket_order %>
  </p>
</div>

app/views/ticket_orders/edit.html.erb
<h1>Editing ticket order</h1>

<%= render "form", ticket_order: @ticket_order %>

<br>

<div>
  <%= link_to "Show this ticket order", @ticket_order %> |
  <%= link_to "Back to ticket orders", ticket_orders_path %>
</div>

app/views/ticket_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ticket orders</h1>

<div id="ticket_orders">
  <%= render @ticket_orders %>
</div>

<%= link_to "New ticket order", new_ticket_order_path %>

app/views/ticket_orders/new.html.erb
<h1>New ticket order</h1>

<%= render "form", ticket_order: @ticket_order %>

<br>

<div>
  <%= link_to "Back to ticket orders", ticket_orders_path %>
</div>

app/views/ticket_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket_order %>

<div>
  <%= link_to "Edit this ticket order", edit_ticket_order_path(@ticket_order) %> |
  <%= link_to "Back to ticket orders", ticket_orders_path %>

  <%= button_to "Destroy this ticket order", ticket_order_path(@ticket_order), method: :delete %>
</div>